### ISSUE TITLE
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

### ISSUE THREAD

**Issue by linfen0** [fishaudio/fish-diffusion#10]
**问题复现流程:**

1. 按照github上的流程安装依赖,
2. 在不加任何args的情况下,直接用依赖环境中的python运行inference.py.

**报错提示:**
`Traceback (most recent call last):
  File "d:\AI_drawer\sovits48k\fish-diffusion\inference.py", line 17, in <module>
    from train import FishDiffusion
  File "d:\AI_drawer\sovits48k\fish-diffusion\train.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "D:\AI_drawer\sovits48k\fish-diffusion\env310\lib\site-packages\matplotlib\__init__.py", line 113, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "D:\AI_drawer\sovits48k\fish-diffusion\env310\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "D:\AI_drawer\sovits48k\fish-diffusion\env310\lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
  File "D:\AI_drawer\sovits48k\fish-diffusion\env310\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。`
**我希望运行后应该发生什么?**

我没有添加任何args,所以他应该报有关args缺少,或是输入音频,模型文件等文件未找到的错误

**通过重装pillow已解决**

**Comment by linfen0** [comment]
我不确定是真缺少args导致的 还是环境没有安装好导致的

**Comment by leng-yue** [comment]
这个是你自己环境爆炸了... 解决了就好 hhh
