### ISSUE TITLE
Poetry install error

### ISSUE THREAD

**Issue by dillfrescott** [fishaudio/fish-diffusion#12]
```
Traceback (most recent call last):
  File "/usr/local/envs/fish/bin/poetry", line 7, in <module>
    from poetry.console import main
  File "/usr/local/envs/fish/lib/python3.10/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/local/envs/fish/lib/python3.10/site-packages/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/usr/local/envs/fish/lib/python3.10/site-packages/poetry/console/commands/__init__.py", line 2, in <module>
    from .add import AddCommand
  File "/usr/local/envs/fish/lib/python3.10/site-packages/poetry/console/commands/add.py", line 8, in <module>
    from .init import InitCommand
  File "/usr/local/envs/fish/lib/python3.10/site-packages/poetry/console/commands/init.py", line 16, in <module>
    from poetry.core.pyproject import PyProjectException
ImportError: cannot import name 'PyProjectException' from 'poetry.core.pyproject' (/usr/local/envs/fish/lib/python3.10/site-packages/poetry/core/pyproject/__init__.py)
ERROR conda.cli.main_run:execute(47): `conda run poetry install` failed. (See above for error)
```

**Comment by dillfrescott** [comment]
Running `pip install poetry` seems to fix the issue...

**Comment by leng-yue** [comment]
Yes, there is some known issues in conda install poetry...

**Comment by dillfrescott** [comment]
Gotcha
