### ISSUE TITLE
pitches_editor.py output and inference.py tensor size discrepancy

### ISSUE THREAD

**Issue by Kickbub** [fishaudio/fish-diffusion#48]
It doesn't always do this but I used pitches_editor.py to extract pitches. I initially thought it was an error with the online GUI but I loaded the .npy from the "pitches_editor" folder to --pitches_path when inferencing and got the same error.

```
Traceback (most recent call last):
  File "C:\Users\Kickbub\Documents\automatic1111\fish-diffusion\tools\diffusion\inference.py", line 438, in <module>
    model.inference(
  File "C:\Users\Kickbub\.conda\envs\Fish\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Kickbub\Documents\automatic1111\fish-diffusion\tools\diffusion\inference.py", line 256, in inference
    wav = self(
  File "C:\Users\Kickbub\.conda\envs\Fish\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Kickbub\.conda\envs\Fish\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Kickbub\Documents\automatic1111\fish-diffusion\tools\diffusion\inference.py", line 99, in forward
    features = self.model.model.forward_features(
  File "C:\Users\Kickbub\Documents\automatic1111\fish-diffusion\fish_diffusion\archs\diffsinger\diffsinger.py", line 92, in forward_features
    features += self.pitch_encoder(pitches)
RuntimeError: The size of tensor a (1579) must match the size of tensor b (1580) at non-singleton dimension 1
```

Weird thing is when I don't use --pitches_path, it works. So it is an issue with pitches_editor.py

Maybe something to do with line 70?

**Comment by Kickbub** [comment]
I put print(audio.shape) in inference.py.

![image](https://user-images.githubusercontent.com/17808984/227853680-5ed5108d-e93c-4834-ba32-b2d285b1a86f.png)

I see that mel_len = audio.shape // 512 but I don't know why it isn't rounding up the second time? It worked on segment 17.

**Comment by leng-yue** [comment]
Can u try `round(audio.shape // 512)` to see if it works?

**Comment by Kickbub** [comment]
With `round(audio.shape[-1] / 512)`
![image](https://user-images.githubusercontent.com/17808984/228072131-6fb4ad59-71c8-49ab-98b7-a177f1af7353.png)

so tensor b size at segment 17 is 1579,
tensor b at segment 18 is 1580

At this point I don't know if it is a problem with inference.py or pitches_editor.py.

**Comment by Kickbub** [comment]
[shynesscenterwav.zip](https://github.com/fishaudio/fish-diffusion/files/11083265/shynesscenterwav.zip)
Here's the .wav file for ppl to test.

**Comment by leng-yue** [comment]
Can't reproduce it in the latest branch. Anyway, I added some code to make sure they have the same length. Do you have time to test the main branch?

**Comment by Kickbub** [comment]
I tested the main branch and it works now.
