### ISSUE TITLE
Inference issue in colab version

### ISSUE THREAD

**Issue by megablocks** [fishaudio/fish-diffusion#99]
Colab version runs fine through training but when trying to get inference, the following error pops up...Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://0fd4daade2bee2fa34.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Traceback (most recent call last):
  File "/content/fish-diffusion/tools/hifisinger/inference.py", line 224, in <module>
    model = HiFiSingerSVCInference(config, args.checkpoint)
  File "/content/fish-diffusion/tools/hifisinger/inference.py", line 25, in __init__
    super().__init__(config, checkpoint, model_cls=model_cls)
  File "/content/fish-diffusion/tools/diffusion/inference.py", line 74, in __init__
    self.model = load_checkpoint(
  File "/content/fish-diffusion/fish_diffusion/utils/inference.py", line 19, in load_checkpoint
    state_dict = torch.load(checkpoint, map_location="cpu")
  File "/content/env/envs/fish_diffusion/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/content/env/envs/fish_diffusion/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "/content/env/envs/fish_diffusion/lib/python3.10/site-packages/gradio/routes.py", line 413, in run_predict
    with utils.MatplotlibBackendMananger():
  File "/content/env/envs/fish_diffusion/lib/python3.10/site-packages/gradio/utils.py", line 788, in __exit__
    matplotlib.use(self._original_backend)
  File "/content/env/envs/fish_diffusion/lib/python3.10/site-packages/matplotlib/__init__.py", line 1233, in use
    plt.switch_backend(name)
  File "/content/env/envs/fish_diffusion/lib/python3.10/site-packages/matplotlib/pyplot.py", line 271, in switch_backend
    backend_mod = importlib.import_module(
  File "/content/env/envs/fish_diffusion/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ipykernel'

**Comment by leng-yue** [comment]
You need to install ipykernel

**Comment by megablocks** [comment]
yes tried that. see screenshot. https://paste.pics/911bed088f1010560cc3cfc31d022d1e

still no luck.

**Comment by leng-yue** [comment]
!source /content/env/bin/activate;\
    conda activate fish_diffusion;\
    pip install ipykernel

**Comment by ayu2hami** [comment]
Did anyone found the solution for this issue? It only happens with HiFiSinger models.
